### ISSUE TITLE
Codeigniteri paigaldamine

### ISSUE THREAD

**Issue by taneltomson** [taneltomson/tartu-library-app#10]
- [x] Hello world rakendus enda arvutis tööle
- [x] Enda lokaalne konfiguratsioon panna .gitignore'i ja luua "soovitatud" vaikeseadistus, mis läheb reposse, kust siis puudu veebilehe url, andmebaasi andmed jms. Vt https://www.codeigniter.com/userguide3/libraries/config.html#environments
- [ ] Dokumenteerida paigaldamisjuhend (kuidas teised tiimiliikmed ja juhendaja saavad asja endale paigaldada). Veebiserveri paigaldamist ilmselt kirjeldama ei pea, aga ära mainida, nt mis andmebaasi kasutatakse, mis apache mod'isid tarvis jms info.

**Comment by mihkelvilismae** [comment]
Codeigniter töötab, samuti ka andmebaas.

Vaja on "Deployment guide teha"
