### ISSUE TITLE
Nõuded konkreetsemaks

### ISSUE THREAD

**Issue by taneltomson** [taneltomson/tartu-library-app#11]
Sellest oli juttu 1. iteratsiooni tagasisides.

Näiteks resolutsioon, teadeteriba, kes täpselt mis tegevusi teha saab jne.

Sisuliselt võtta #8-st info ja see konkreetseteks nõueteks kirjutada

**Comment by mihkelvilismae** [comment]
Arvatavasti hea. Panen kinni.
