### ISSUE TITLE
Androidi rakendusele CI sisse seada

### ISSUE THREAD

**Issue by taneltomson** [taneltomson/tartu-library-app#16]
- [x] Asi CI-s tööle saada
- [ ] Dokumentatsiooni kirjeldus
- [ ] Dokumentatsiooni juhend, kuidas juhendaja saab meie Android rakenduse paigaldada või ise CI-sse lükata (conf, eeldused jne)
- [ ] ...

**Comment by mihkelvilismae** [comment]
Ülejäänu teeme siin: #22
