### ISSUE TITLE
Waffle'i kasutuselevõtt

### ISSUE THREAD

**Issue by taneltomson** [taneltomson/tartu-library-app#18]
Kas te olete nõus waffle'i kasutusele võtmisega? Igaüks saab ise valida, kas kasutab Githubi või Waffle'it või mõlemat läbisegi. Waffle'is - nagu Trellos - hea ülevaade to do -> ready to do -> in progress -> done; aga Githubis imo parem taske kirjutada ja hallata. Ligi pääsete (ka juhendaja) lingilt:
[Waffle](https://waffle.io/taneltomson/tartu-library-app/join)

- [ ] **Lisada wikisse link, kirjeldus ja info Waffle'i kohta juhendaja jaoks.**

**Comment by mihkelvilismae** [comment]
See Githubi oma mulle sobib, seega võib minu poolest selle kinni panna.
