### ISSUE TITLE
Andmebaasi ligipääs

### ISSUE THREAD

**Issue by taneltomson** [taneltomson/tartu-library-app#9]
- [x] Anda teistele ligipääs andmebaasile (kas terve andmebaas, kui mõistlikud mahud või pigem väike osa näidiseks)
- [x] Selgitada, mis, kus, või jagada dokumentatsiooni vms

**Comment by mihkelvilismae** [comment]
Andmebaasiga sisuline tutvus tehtud. 

Dumpi kõigist andmetest teha ei saa, samuti oleks see ebapraktiline.

Natukene pean veel süvenema ning raamatukogu töötajatega konsulteerima ja  siis loodetavasti saame Annelinna raamatukogu lasteosakonna alamosa.

Hetkel peab andmebaasiga tegelemiseks Tartu raamatukogu võrgus sees olema (pakuti ka võimalust meile kasutada anda arvuti. Uurin ka seda).

Vahemikus 12.10 - 13.10 üritan saada meile vajalikud andmed.

**Comment by mihkelvilismae** [comment]
Oleme saanud ligipääsu andmebaasile (selleks peame olema raamatukogu võrgus), samuti saime dokumentatsiooni.

(paroole ja usereid küsige minu käest)
